### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by dhx71** [wernerd/GoRTP#4]
I have forked your GoRTP library and noticed that there are no licences attached to your project. Would you consider adding a licence such as common creative or MIT?

**Comment by wari** [comment]
Yes please, having no license is confusing as we don't know what we can or cannot do with it.

**Comment by wernerd** [comment]
Each file in the project has a license header. Please chek. Each
file uses GPL 3


Werner

Am 16.10.2015 um 04:27 schrieb Wari Wahab:
> Yes please, having no license is confusing as we don't know what we can or cannot do with it.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/wernerd/GoRTP/issues/4#issuecomment-148578179>.
> 

-- 
Werner Dittmann
email: Werner.Dittmann@t-online.de
cell:  +49 173 44 37 659
PGP key: 82EF5E8B
